---
python_tmp: /tmp
python_url: https://www.python.org/ftp/python/3.7.0/Python-3.7.0.tgz
python_dir: /tmp/Python-3.7.0
python_yum:
   - wget
   - zlib-devel
   - bzip2-devel
   - openssl-devel
   - ncurses-devel
   - sqlite-devel
   - readline-devel
   - tk-devel
   - gcc